# fly.toml app configuration file generated for swiftflow-app on 2026-02-26T19:58:03+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swiftflow-app'
primary_region = 'iad'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_locations,read_orders,write_app_proxy,write_products'
  SHOPIFY_API_KEY = 'c51a636b3f088fcdb03a770d4ee64992'
  SHOPIFY_APP_URL = 'https://logiclooms.io'


[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512

  [processes]
  app = "npm run docker-start"
