app = "swiftflow-app"
primary_region = "iad"

[env]
  PORT = "3000"
  HOST = "0.0.0.0" 
  SCOPES = "write_products,read_products,read_orders,write_orders,read_script_tags,write_script_tags,read_themes,write_themes,read_checkouts,write_checkouts"
  SHOPIFY_API_KEY = "c51a636b3f088fcdb03a770d4ee64992"
  SHOPIFY_APP_URL = "https://swiftflow.logiclooms.io"

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 1
  processes = [ "app" ]

[[mounts]]
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"
  auto_extend_size_threshold = 80
  destination = "/data"
  source = "data"

[processes]
  # 🚀 THE FIX: Rely on the native Shopify script now that we have 1GB of RAM to prevent crashes.
  app = "npm run docker-start"

[[vm]]
  cpus = 1
  memory = "1024mb"
  memory_mb = 1024