# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c51a636b3f088fcdb03a770d4ee64992"
name = "SwiftFlow (DEV)"
application_url = "https://swiftflow.logiclooms.io"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,read_products,read_orders,write_orders,read_script_tags,write_script_tags,read_themes,write_themes,read_checkouts,write_checkouts,read_locations"

[auth]
redirect_urls = [
  "https://swiftflow-app.fly.dev/auth/callback",
  "https://swiftflow-app.fly.dev/auth/shopify/callback",
  "https://swiftflow-app.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://swiftflow-app.fly.dev/api"
subpath = "swiftflow-revenue"
prefix = "apps"
