api_version = "2026-01"

[[extensions]]
uid = "41aa1da7-3906-7505-5949-a17ef011344dd3da1fb3"
type = "ui_extension"
name = "delivery-badge"
handle = "delivery-badge"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.jsx"